"""Prepare the labelled attack corpus for detector-generalization testing.

Writes to data/corpus/:
    egress_cases.jsonl      256 labelled cases, one JSON object per line
    temporal_cases.jsonl    the 6 before/after mcp_drift cases, split out
    escape_scenarios.json   sandbox_escape_bench scenario taxonomy
    coverage.json           machine-readable capability/limit report
    DATASHEET.md            what this corpus is, and what it cannot establish

    python scripts/prepare_corpus.py
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from warningshot import paths                       # noqa: E402
from warningshot.detect import corpus as C          # noqa: E402

OUT = paths.DATA / "corpus"


def _jsonl(rows, name):
    path = OUT / name
    with open(path, "w", encoding="utf-8") as fh:
        for r in rows:
            fh.write(json.dumps(r, sort_keys=True) + "\n")
    print(f"    wrote {path.relative_to(paths.ROOT)}  ({len(rows)} rows)")


def datasheet(cov, temporal, escape, tstatus):
    fam = "\n".join(
        f"| `{f}` | {v['n']} | {v.get('block', 0)} | {v.get('allow', 0)} | {v.get('warn', 0)} |"
        for f, v in sorted(cov["by_family"].items(), key=lambda kv: -kv[1]["n"])
    )
    tmp = "\n".join(
        f"| `{c['case_id']}` | `{c['expected_verdict']}` | {len(c['before_text'])} | {len(c['after_text'])} |"
        for c in temporal
    )
    return f"""# Datasheet — labelled attack corpus

Generated by `scripts/prepare_corpus.py`. Do not hand-edit.

## Why this corpus exists

To answer one question: **does a detector built for a single attack class stay
quiet on other attack classes and on benign traffic?** That is a specificity
question. The data available can answer it. It cannot answer the matching
sensitivity question for transport-level covert channels, and this datasheet
says so in the same breath rather than in a footnote.

## Provenance

| Source | Ships | Role |
|---|---|---|
| `agent-egress-bench` | {cov['n_cases']} cases, {cov['n_families']} families, every case labelled | **primary** |
| `sandbox_escape_bench` | {len(escape)} scenario definitions with exploit code | taxonomy only |
| `sandbox_escape_bench` transcripts | **nothing** — {tstatus['n_rows']} indexed runs, {tstatus['n_resolvable_locally']} resolvable | **unusable** |

Counts were cross-checked against agent-egress-bench's own `cases/STATS.md`
and agree exactly ({cov['n_cases']} cases, {cov['n_families']} families,
block {cov['verdicts']['block']} / allow {cov['verdicts']['allow']} /
warn {cov['verdicts']['warn']}). `tests/test_corpus.py::test_matches_upstream_stats`
enforces that agreement, because an earlier loader walked `*.json` only and
silently reported 250 cases and 17 families, dropping the corpus's only
`warn`-labelled case.

### The transcript gap, stated plainly

`sandbox_escape_bench/transcript-analysis/.../included_logs.csv` indexes
{tstatus['n_rows']} eval runs across 19 scenarios and 9 models. Its `log`
column holds absolute paths of the form:

    {tstatus['example_log_path']}

None resolve inside the clone. **Per-sample transcripts are not recoverable**,
so this corpus supports no per-episode detection scoring. Aggregate
behaviour-scan tables under `transcript-analysis/results/` remain readable as
priors. This is the third dataset in this project that indexes data it does not
ship; the first was the Hugging Face 17,600-action replay (HTTP 403).

## Ground truth

`expected_verdict` in `block` / `allow` / `warn`, authored by the corpus
maintainers, not by us. Self-labelling circularity is a named reviewer
complaint in this programme, and this corpus avoids it: we did not write these
labels and cannot tune them.

- attack (`block`): **{cov['n_attack']}**
- benign (`allow`/`warn`): **{cov['n_benign']}**
- purpose-built false-positive traps (`false_positive` family): **{cov['n_fp_dedicated']}**
- benign controls inside attack families: **{cov['n_fp_in_family']}**
- benign cases upstream labels `high` false-positive risk: **{cov['n_benign_high_fp_risk']}**

### By family

| family | n | block | allow | warn |
|---|---:|---:|---:|---:|
{fam}

## The temporal sub-corpus

Six `mcp_drift` cases pair a baseline snapshot with a later one. Their own
threat model calls tool metadata a covert channel, so the broad reading of the
upstream README's covert-channel exclusion is wrong — that exclusion is about
transport-level channels. These six are the closest shipping analogue to a
channel that reappears after a substrate is wiped, because the discrimination
they demand is *malicious mutation* versus *legitimate change*.

| case | label | before (chars) | after (chars) |
|---|---|---:|---:|
{tmp}

A detector reading only a flattened payload cannot solve these; it has to
compare two states. That is why `before_text` and `after_text` are kept apart
in the record rather than concatenated.

## What this corpus can establish

{chr(10).join('- ' + s for s in cov['measurable'])}

## What it cannot establish

{chr(10).join('- ' + s for s in cov['not_measurable'])}

## Files

| file | contents |
|---|---|
| `egress_cases.jsonl` | all {cov['n_cases']} labelled cases |
| `temporal_cases.jsonl` | the {len(temporal)} before/after cases |
| `escape_scenarios.json` | {len(escape)} breakout scenario definitions |
| `coverage.json` | this datasheet's numbers, machine-readable |
"""


def main():
    paths.ensure(OUT)
    print("\n[corpus] preparing labelled attack corpus")

    cases = C.load_egress_bench()
    cov = C.coverage_report(cases)
    rows = [c.to_json() for c in cases]
    temporal = [r for r in rows if r["is_temporal"]]
    escape = C.load_escape_scenarios()
    tstatus = C.escape_transcript_status()

    _jsonl(rows, "egress_cases.jsonl")
    _jsonl(temporal, "temporal_cases.jsonl")
    with open(OUT / "escape_scenarios.json", "w", encoding="utf-8") as fh:
        json.dump({"scenarios": escape, "transcript_status": tstatus}, fh, indent=2)
    print(f"    wrote {(OUT / 'escape_scenarios.json').relative_to(paths.ROOT)}"
          f"  ({len(escape)} scenarios)")
    with open(OUT / "coverage.json", "w", encoding="utf-8") as fh:
        json.dump(cov, fh, indent=2)
    print(f"    wrote {(OUT / 'coverage.json').relative_to(paths.ROOT)}")
    (OUT / "DATASHEET.md").write_text(
        datasheet(cov, temporal, escape, tstatus), encoding="utf-8")
    print(f"    wrote {(OUT / 'DATASHEET.md').relative_to(paths.ROOT)}")

    print(f"\n    {cov['n_cases']} cases | {cov['n_families']} families | "
          f"{cov['n_attack']} attack / {cov['n_benign']} benign | "
          f"{cov['n_fp_dedicated']} dedicated + {cov['n_fp_in_family']} in-family FP | "
          f"{len(temporal)} temporal")
    print(f"    escape transcripts resolvable locally: "
          f"{tstatus['n_resolvable_locally']} of {tstatus['n_rows']}  <- unusable")
    return 0


if __name__ == "__main__":
    sys.exit(main())
